#!/usr/bin/env python3
from subprocess import run
from os.path import join,basename,splitext
from os import getuid,listdir
from sys import argv

if len(argv)==1:
    run(['zenity','--info',"--text=You can't launch this program from the menu",'--title=Error'])
    exit(1)

PRESENTATION='presentation'
DOCUMENT='document'
SPREADSHEET='spreadsheets'
types={'.pptx':PRESENTATION,'.ppt':PRESENTATION,'.docx':DOCUMENT,'.doc':DOCUMENT,'.xls':SPREADSHEET,'.xlsx':SPREADSHEET}

folder=join('/run','user',str(getuid()),'gvfs')
files=listdir(folder)[0]
if len(files)==0:
    run(['zenity', '--info', "--text=You must mount Google Drive in Nautilus first", '--title=Error'])
    exit(1)
folder=join(folder,files)

old_files=listdir(folder)
run(['cp',argv[1],join(folder,basename(argv[1]))],check=True)
new_files=listdir(folder)
for file in old_files:
    new_files.remove(file)
run(['xdg-open',f'https://docs.google.com/{types[splitext(argv[1])[1]]}/d/{new_files[0]}/edit'],check=True)
